### PR TITLE
Update GRPC Version

### PR DESCRIPTION
**Pull request by yeshwanthvshenoy**
GRPC folks have released a newer version. It is time we update as well.

Link to release: [Github](https://github.com/grpc/grpc-java/releases) | [Maven](https://mvnrepository.com/artifact/io.grpc/grpc-core)

### CODE REVIEW

**Comment by ST-DDT** [comment]
Thanks for your contribution.

**Comment by yeshwanthvshenoy** [comment]
Cool 👍

**Comment by yeshwanthvshenoy** [comment]
@ST-DDT can we merge this? Also is there a release expected on the cards?

**Comment by ST-DDT** [comment]
> @ST-DDT can we merge this?

This is up to @yidongnan . It is possible that we first create a release with grpc 1.21 before we move forward to the this one. Is there a feature in the new grpc version that you need or is there another reasons why we should include it ASAP?

> Also is there a release expected on the cards?

Currently there is no release scheduled atm.
I would like to create and merge a fix for #240 first before we release [v2.5.0](https://github.com/yidongnan/grpc-spring-boot-starter/milestone/3).

**Comment by ST-DDT** [comment]
https://github.com/grpc/grpc-java/releases/tag/v1.22.1
has been released.

**Comment by yeshwanthvshenoy** [comment]
> 
> This is up to @yidongnan . It is possible that we first create a release with grpc 1.21 before we move forward to the this one. Is there a feature in the new grpc version that you need or is there another reasons why we should include it ASAP?
> 

We are wanting [this](https://github.com/grpc/grpc-java/pull/5873) fix actually since it confuses lot of devs during debugging. If we upgrade grpc, we want to keep the starter pack in level terms as well. That is the reason.

> > Also is there a release expected on the cards?
> 
> Currently there is no release scheduled atm.
> I would like to create and merge a fix for #240 first before we release [v2.5.0](https://github.com/yidongnan/grpc-spring-boot-starter/milestone/3).

Okay cool. Will keep monitoring for the starter pack for new release.

> https://github.com/grpc/grpc-java/releases/tag/v1.22.1
> has been released.

Do you suggest we upgrade to this?

**Comment by ST-DDT** [comment]
> Do you suggest we upgrade to this?

Yes

**Comment by yeshwanthvshenoy** [comment]
> > Do you suggest we upgrade to this?
> 
> Yes

It's done. Hoping we can see a release soon as I can see #240 fix is merged.

**Comment by yeshwanthvshenoy** [comment]
Cool. Thanks @ST-DDT 👍 . Tagging @yidongnan here so he can merge when available.

**Comment by ST-DDT** [comment]
It is not necessary to ping everybody.
We are well aware of everything new here and we will get to it once we have the time for it.

**Pull request merged**
