### PR TITLE
Add nacos example

### PR DESCRIPTION
**Pull request by xieyucan**
add nacos example

### CODE REVIEW

**Comment by ST-DDT** [comment]
Nice. I'll have a look when I have some free time.
Could you post a (docker) command here that I can use to spin up a nacos registry to test the example?

**Comment by xieyucan** [comment]
> Nice. I'll have a look when I have some free time.
> Could you post a (docker) command here that I can use to spin up a nacos registry to test the example?

Thank you for your feedback, the docker command in the next :
docker pull nacos/nacos-server
docker run --env MODE=standalone --name nacos -d -p 8848:8848 nacos/nacos-server

You can access this URL to verify that Nacos started successfully:
http://localhost:8848/nacos

Please give me more advice and contact me if you have any questions.

**Comment by ST-DDT** [comment]
Thanks for your fast response. That really helps me to integrate it the test examples script to ensure that the example doesnt break unnoticed.

**Review by ST-DDT — APPROVED** [review]

**Comment by ST-DDT** [comment]
Thanks for your contribution

**Pull request merged**
