### PR TITLE
suggestion: switch to shaded netty dependency, see #139

### PR DESCRIPTION
**Pull request by uweschaefer**
https://github.com/yidongnan/grpc-spring-boot-starter/issues/139

feel free to just drop this if you don't think, it is a good idea.

### CODE REVIEW

**Comment by ST-DDT** [comment]
I dont think we should switch to shaded entirely, but maybe we can add the neccessary auto config classes. Then the devs only have to switch their depencies and have still full support from this lib.

**Comment by uweschaefer** [comment]
not sure how to do that, as some of the classes are used in bean provider methods themselves.

**Comment by yidongnan** [comment]
I also think it would be better to do this through automatic configuration. By using the ``@ConditionalOnClass`` annotation to inject the implementation class based on the dependency, but there may be some duplicate code, if there is a way to solve the code duplication here will be better.

**Comment by ST-DDT** [comment]
Do you want to give it a try?

**Comment by uweschaefer** [comment]
i would not know how without significant duplication. probably, some else should open a different PR for that.

**Comment by ST-DDT** [comment]
Thanks for your contribution anyway. I don't know whether I can avoid the duplication myself either.
I will probably try to do that in a few days unless @yidongnan wants to go ahead.

**Pull request closed without merging**
