### PR TITLE
Adding configuration/support for transport security

### PR DESCRIPTION
**Pull request by backjo**
This change is [Reviewable](https://reviewable.io/reviews/yidongnan/grpc-spring-boot-starter/36)

### CODE REVIEW

**Comment by yidongnan** [comment]
@backjo There is no client TLS configuration?

**Comment by backjo** [comment]
Client TLS is controlled via the usePlaintext property on a channel, which clients can already set

**Comment by yidongnan** [comment]
@backjo Merged, thanks for the PR!

**Comment by backjo** [comment]
Awesome! No problem. Any chance you could publish a new release? Trying not to use a SNAPSHOT version in my project if I can avoid it :)

**Comment by yidongnan** [comment]
@backjo You can use 1.1.0.RELEASE now.

**Pull request merged**
