### PR TITLE
Change auto configs to use `@Configuration(proxyBeanMethods = false)`

### LINKED ISSUE #379: [GraalVM Support] Disabling CGLIB proxies for autoconfiguration
**The problem**

Currently Spring Boot applications are unable to run with GraalVM and native image due to CGLIB proxies on the autoconfiguration classes. The current error is observed on startup:
```
2020-07-10 13:54:17.715 ERROR 1412912 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanDefinitionStoreException: @Configuration classes need to be marked as proxyBeanMethods=false. Found: [net.devh.boot.grpc.common.autoconfigure.GrpcCommonCodecAutoConfiguration, net.devh.boot.grpc.client.autoconfigure.GrpcClientMetricAutoConfiguration, net.devh.boot.grpc.client.autoconfigure.GrpcClientSecurityAutoConfiguration, net.devh.boot.grpc.client.autoconfigure.GrpcClientAutoConfiguration, net.devh.boot.grpc.client.autoconfigure.GrpcClientHealthAutoConfiguration, net.devh.boot.grpc.server.autoconfigure.GrpcServerMetricAutoConfiguration, net.devh.boot.grpc.server.autoconfigure.GrpcServerAutoConfiguration, net.devh.boot.grpc.server.autoconfigure.GrpcServerFactoryAutoConfiguration]
```

**The solution**

Set the proxyBeanMethods=false on the `@Configuration` annotation on the Autoconfiguration classes

### PR DESCRIPTION
**Pull request by ST-DDT**
This should improve compatibility with GraalVM.

Fixes #379

@lthd92 Can you please verify whether this is all that needs to be done for GraalVM support?

### CODE REVIEW

**Comment by ST-DDT** [comment]
TODO: Check for this.methodCall()

**Comment by lthd92** [comment]
> This should improve compatibility with GraalVM.
> 
> Fixes #379
> 
> @lthd92 Can you please verify whether this is all that needs to be done for GraalVM support?

Will verify it later today :+1:

**Comment by lthd92** [comment]
> > > This should improve compatibility with GraalVM.
> > > Fixes #379
> > > @lthd92 Can you please verify whether this is all that needs to be done for GraalVM support?
> > 
> > 
> > Will verify it later today +1
> 
> Successfully builds and start a native image built on a ubuntu system.
> 
> Instead of a 2-3 second startup time we now have:
> 
> ```
>   .   ____          _            __ _ _
>  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
> ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
>  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
>   '  |____| .__|_| |_|_| |_\__, | / / / /
>  =========|_|==============|___/=/_/_/_/
>  :: Spring Boot ::                        
> 
> 2020-07-16 23:24:11.097  INFO 2134349 --- [           main] .l.GraalGrpcSpringBootStarterApplication : Starting GraalGrpcSpringBootStarterApplication on x with PID 2134349 (/home/x/git/graalvm-grpc-starter/build/native/grpc-graal started by x in /home/x/git/graalvm-grpc-starter/build/native)
> 2020-07-16 23:24:11.097  INFO 2134349 --- [           main] .l.GraalGrpcSpringBootStarterApplication : No active profile set, falling back to default profiles: default
> 2020-07-16 23:24:11.193  INFO 2134349 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 2 endpoint(s) beneath base path '/actuator'
> 2020-07-16 23:24:11.198  WARN 2134349 --- [           main] i.m.c.i.binder.jvm.JvmGcMetrics          : GC notifications will not be available because MemoryPoolMXBeans are not provided by the JVM
> 2020-07-16 23:24:11.208  INFO 2134349 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port(s): 8080
> 2020-07-16 23:24:11.210  INFO 2134349 --- [           main] .l.GraalGrpcSpringBootStarterApplication : Started GraalGrpcSpringBootStarterApplication in 0.12 seconds (JVM running for 0.123)
> ```

However connection to the server doesnt seem to work.
Getting
```
"error": "14 UNAVAILABLE: failed to connect to all addresses"
```

**Comment by ST-DDT** [comment]
I assume that this is caused by some missing configurations (reflection or alike).
Lets get this merged, as it improves startup times (a tiny bit) even without GraalVM native image.

**Pull request merged**
