### PR TITLE
Add AutoConfiguration.imports for basic spring boot v3.0 support

### PR DESCRIPTION
**Pull request by genuss**
Hello!
I'd like to add the new style of auto-configurations declaration which appeared in [spring boot 2.7](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#auto-configuration-registration) This version of spring supports old-style too, but [spring boot 3.x](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M5-Release-Notes#auto-configuration-registration) won't support `spring.factories` anymore. I don't delete auto-configurations from `spring.factories` yet, as current baseline is spring boot 2.6.x.
I'd like to merge this as I'm interested in preparing to 3.x release and this is a first step of it.

### CODE REVIEW

**Comment by ST-DDT** [comment]
Nice! Have you tested whether having both causes issues?
E.g. beans being initialized twice...

**Comment by genuss** [comment]
Well, I didn't do thorough testing, but checked all my in-house autoconfigurations from work and some open-source ones. And I didn't find anything wrong.
For duplicate autoconfigurations there is `AutoConfigurationImportSelector#removeDuplicates`, so I don't think there can be issues

**Comment by ST-DDT** [comment]
When @yidongnan or I have time to test and review it.
I hope soonish.

**Comment by QB-NemanjaTozic** [comment]
Just to note that since Spring Boot 3 doesn't support `spring.factories`, the library doesn't currently work out-of-the-box with Spring Boot 3.0.0.

Workaround until this is merged is to import all of the configurations that are listed in current `spring.factories`:

```
@Configuration
@ImportAutoConfiguration({
    net.devh.boot.grpc.client.autoconfigure.GrpcClientAutoConfiguration.class,
    net.devh.boot.grpc.client.autoconfigure.GrpcClientMetricAutoConfiguration.class,
    net.devh.boot.grpc.client.autoconfigure.GrpcClientHealthAutoConfiguration.class,
    net.devh.boot.grpc.client.autoconfigure.GrpcClientSecurityAutoConfiguration.class,
    net.devh.boot.grpc.client.autoconfigure.GrpcClientTraceAutoConfiguration.class,
    net.devh.boot.grpc.client.autoconfigure.GrpcDiscoveryClientAutoConfiguration.class,

    net.devh.boot.grpc.common.autoconfigure.GrpcCommonCodecAutoConfiguration.class,
    net.devh.boot.grpc.common.autoconfigure.GrpcCommonTraceAutoConfiguration.class,

    net.devh.boot.grpc.server.autoconfigure.GrpcAdviceAutoConfiguration.class,
    net.devh.boot.grpc.server.autoconfigure.GrpcHealthServiceAutoConfiguration.class,
    net.devh.boot.grpc.server.autoconfigure.GrpcMetadataConsulConfiguration.class,
    net.devh.boot.grpc.server.autoconfigure.GrpcMetadataEurekaConfiguration.class,
    net.devh.boot.grpc.server.autoconfigure.GrpcMetadataNacosConfiguration.class,
    net.devh.boot.grpc.server.autoconfigure.GrpcMetadataZookeeperConfiguration.class,
    net.devh.boot.grpc.server.autoconfigure.GrpcReflectionServiceAutoConfiguration.class,
    net.devh.boot.grpc.server.autoconfigure.GrpcServerAutoConfiguration.class,
    net.devh.boot.grpc.server.autoconfigure.GrpcServerFactoryAutoConfiguration.class,
    net.devh.boot.grpc.server.autoconfigure.GrpcServerMetricAutoConfiguration.class,
    net.devh.boot.grpc.server.autoconfigure.GrpcServerSecurityAutoConfiguration.class,
    net.devh.boot.grpc.server.autoconfigure.GrpcServerTraceAutoConfiguration.class
})
class GrpcConfig {}
```

**Comment by amitbansal26** [comment]
> @amitbansal26 This is a very simple project that I do for some internal reasons (on my private profile) and has a very simple use of the library, but hope it's something useful for you:
> 
> https://github.com/NemanjaT/airsoft-iam
> 
> This is the workaround I was talking about: https://github.com/NemanjaT/airsoft-iam/blob/main/src/main/java/com/ntozic/airsoft/iam/config/grpc/GrpcConfig.java

Thanks So much this surely helps !!!

**Comment by renatosilvarosa** [comment]
Other workaround: create your own `org.springframework.boot.autoconfigure.AutoConfiguration.imports` file under `META-INF/spring` and add the list of classes currently in `spring.factories`.

**Review by ST-DDT — APPROVED** [review]

**Comment by bdevapatla** [comment]
> @Configuration
> @ImportAutoConfiguration({
>     net.devh.boot.grpc.client.autoconfigure.GrpcClientAutoConfiguration.class,
>     net.devh.boot.grpc.client.autoconfigure.GrpcClientMetricAutoConfiguration.class,
>     net.devh.boot.grpc.client.autoconfigure.GrpcClientHealthAutoConfiguration.class,
>     net.devh.boot.grpc.client.autoconfigure.GrpcClientSecurityAutoConfiguration.class,
>     net.devh.boot.grpc.client.autoconfigure.GrpcClientTraceAutoConfiguration.class,
>     net.devh.boot.grpc.client.autoconfigure.GrpcDiscoveryClientAutoConfiguration.class,
> 
>     net.devh.boot.grpc.common.autoconfigure.GrpcCommonCodecAutoConfiguration.class,
>     net.devh.boot.grpc.common.autoconfigure.GrpcCommonTraceAutoConfiguration.class,
> 
>     net.devh.boot.grpc.server.autoconfigure.GrpcAdviceAutoConfiguration.class,
>     net.devh.boot.grpc.server.autoconfigure.GrpcHealthServiceAutoConfiguration.class,
>     net.devh.boot.grpc.server.autoconfigure.GrpcMetadataConsulConfiguration.class,
>     net.devh.boot.grpc.server.autoconfigure.GrpcMetadataEurekaConfiguration.class,
>     net.devh.boot.grpc.server.autoconfigure.GrpcMetadataNacosConfiguration.class,
>     net.devh.boot.grpc.server.autoconfigure.GrpcMetadataZookeeperConfiguration.class,
>     net.devh.boot.grpc.server.autoconfigure.GrpcReflectionServiceAutoConfiguration.class,
>     net.devh.boot.grpc.server.autoconfigure.GrpcServerAutoConfiguration.class,
>     net.devh.boot.grpc.server.autoconfigure.GrpcServerFactoryAutoConfiguration.class,
>     net.devh.boot.grpc.server.autoconfigure.GrpcServerMetricAutoConfiguration.class,
>     net.devh.boot.grpc.server.autoconfigure.GrpcServerSecurityAutoConfiguration.class,
>     net.devh.boot.grpc.server.autoconfigure.GrpcServerTraceAutoConfiguration.class
> })

This file doesn't exist anymore. Also, has this config already been merged to grpc-spring-boot-starter?

**Comment by ctdillon** [comment]
@bdevapatla It's been merged, but apparently hasn't made it into a tagged release yet. You can create this file in your own project, and use that until it is.

**Comment by danHayworth** [comment]
did anyone find that after adding these imports you get the Server port already in use when running `mvn test` ?

**Comment by MissakaI-ObjectOne** [comment]
For anyone having the issue `io.grpc.StatusRuntimeException: UNAVAILABLE: Could not find server: myServer` even after adding the auto configuration to match the Spring Boot 3 in you grpc client

Try adding `@EnableConfigurationProperties(value = {GrpcChannelsProperties.class})` to your grpc client.

**Comment by lmcdasi** [comment]
I do not think having GrpcConfig with all AutoConfig is correct. Not all projects have grpc client & server at the same time.

If I have grpc client or grpc server, then I will end up having a meta-data exception since the corresponding jar file is missing.

Until it get's fix I think that each project needs to add:

 META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports

containing the exact set of the AutoConfig files, client or server or both.

**Pull request merged**
