### PR TITLE
Upgrade GRPC version due to new feature introduced in 1.40.0 version.

### PR DESCRIPTION
**Pull request by luankevinferreira**
When I'm using the following plugin with grpc-spring-boot-starter and try to use the 1.40.1 version of grpc-java, an error occurs as mentioned in this issue https://github.com/grpc/grpc-java/issues/8523.

```xml
                         <plugin>
				<groupId>org.xolstice.maven.plugins</groupId>
				<artifactId>protobuf-maven-plugin</artifactId>
				<version>${protobuf-maven-plugin.version}</version>
				<configuration>
					<protocArtifact>
						com.google.protobuf:protoc:3.17.3:exe:${os.detected.classifier}
					</protocArtifact>
					<pluginId>grpc-java</pluginId>
					<pluginArtifact>
						io.grpc:protoc-gen-grpc-java:1.40.1:exe:${os.detected.classifier}
					</pluginArtifact>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>compile</goal>
							<goal>compile-custom</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

```

### CODE REVIEW

**Review by ST-DDT — DISMISSED** [review]
Looks good to me. Thanks for your contribution.

**Comment by ST-DDT** [comment]
Please note that you can overwrite the dependency versions using the grpc-bom.
I use this library 2.12 along with grpc 1.40 without any issues.

**Comment by ST-DDT** [comment]
@luankevinferreira Could you please check why the tests are failing?
Or should I take over from this point?

**Comment by luankevinferreira** [comment]
@ST-DDT I've looked at the logs and seemed to be some temporary failure with host name resolution, I've updated the branch and now is requiring an approval of the workflow to be run, could you please approve?

**Comment by ST-DDT** [comment]
````txt
SelfNameResolverConnectionTest > testSelfConnection() FAILED
    io.grpc.StatusRuntimeException: UNAVAILABLE: Unable to resolve host self
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at net.devh.boot.grpc.test.proto.TestServiceGrpc$TestServiceBlockingStub.normal(TestServiceGrpc.java:579)
        at net.devh.boot.grpc.test.setup.SelfNameResolverConnectionTest.testSelfConnection(SelfNameResolverConnectionTest.java:62)

        Caused by:
        java.lang.RuntimeException: java.net.UnknownHostException: self
            at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
            at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
            at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
            at java.lang.Thread.run(Thread.java:748)

            Caused by:
            java.net.UnknownHostException: self
                at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
                at java.net.InetAddress.getAllByName(InetAddress.java:1193)
                at java.net.InetAddress.getAllByName(InetAddress.java:1127)
                at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:631)
                at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
                ... 5 more
````

AFAICT the `SelfNameResolver` does not work as expected anymore.

**Comment by luankevinferreira** [comment]
@ST-DDT does this error was caused by the change of version or is something internally?

**Comment by ST-DDT** [comment]
This failure is related to the change in grpc version, although I'm not sure why.
From a technical perspective the code should not attempt the `DnsNameResolver` and instead use the `SelfResolver`.
I assume this is related to the NameResolverRegistry bean (either not working or being a copy instead of a reference).
Alternatively, there was a change regarding missing schemes in the address urls.

**Comment by ST-DDT** [comment]
I checked the respective code and found https://github.com/grpc/grpc-java/pull/8323 to be responsible for the breakage.
But I also found:

````java
/**
     * Creates a {@link NameResolver} for the given target URI, or {@code null} if the given URI
     * cannot be resolved by this factory. The decision should be solely based on the scheme of the
     * URI.
     *
     * @param targetUri the target URI to be resolved, whose scheme must not be {@code null}
     * @param args other information that may be useful
     *
     * @since 1.21.0
     */
````

The `SelfNameResolverFactory` does not abide by this rule and also uses the full uri, thus being an invalid implementation.

````java
    public NameResolver newNameResolver(final URI targetUri, final Args args) {
        if (SELF_SCHEME.equals(targetUri.getScheme()) || targetUri.toString().equals(SELF_SCHEME)) {
            return new SelfNameResolver(this.properties, args);
        }
        return null;
    }
````

The following needs to be done to fix this:
* Edit `SelfNameResolverFactory` to only use the scheme
* Search for all tests that use the client name `self` or use `self` as address and set their address to `self:self` (or similar)
* Search and update the documentation for [hints regarding name resolution](https://yidongnan.github.io/grpc-spring-boot-starter/en/client/configuration.html#choosing-the-target)

@luankevinferreira Would you like to give it a try?

**Comment by luankevinferreira** [comment]
@ST-DDT I did some changes, could you please approve the workflow and review if is everything ok?

**Review by ST-DDT — CHANGES_REQUESTED** [review]
The original test was intended to test both name based logic and address based lookup.
Now that the name based resolution is no longer be possible we can simplify it to one test.

**Review by ST-DDT — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
