### PR TITLE
merge GrpcMetadtaxxxConfiguration

### PR DESCRIPTION
**Pull request by Cczzzz**
#564

### CODE REVIEW

**Comment by ST-DDT** [comment]
Looks good to me. I'll do an in depth review after my holidays.

**Comment by ST-DDT** [comment]
Please run `./gradlew spotlessApply` and commit the generated changes.
Also please rename `GrpcMetadataConfiguration` to `GrpcCloudMetadataConfiguration`.

**Comment by Cczzzz** [comment]
> 请运行`./gradlew spotlessApply`并提交生成的更改。
> 也请重命名`GrpcMetadataConfiguration`为`GrpcCloudMetadataConfiguration`.

ok

**Comment by ST-DDT** [comment]
This failed for Eureka for me. I'll have another look at it soon.

**Review by ST-DDT — CHANGES_REQUESTED** [review]
[`EurekaAutoServiceRegistration`](https://github.com/spring-cloud/spring-cloud-netflix/blob/main/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/serviceregistry/EurekaAutoServiceRegistration.java#L67) does not publish the `InstancePreRegisteredEvent`, so it does not work that easily.

**Pull request closed without merging**
