### PR TITLE
feat: add metadata size config for server

### PR DESCRIPTION
**Pull request by jbf154**
Added a new property to control the maximum metadata size for incoming gRPC requests to the server.

### CODE REVIEW

**Comment by jbf154** [comment]
> Thanks for your contribution

No problem. Is there a timeline on the next release?

**Comment by ST-DDT** [comment]
Not yet. If you need one soon, we could split the current milestone to speed things up.

**Comment by jbf154** [comment]
> Not yet. If you need one soon, we could split the current milestone to speed things up.

If you think it'll be in the next month or so, I can wait.  If not, splitting the milestone would be awesome. Appreciate it.

**Comment by ST-DDT** [comment]
FYI: I try to finish the remaining issues in the next two weeks and do a release afterwards.

**Comment by jbf154** [comment]
> FYI: I try to finish the remaining issues within the next two weeks and do a release afterwards.

Thanks!

**Pull request merged**
